services:
  web:
    build: web-server/
    #ports:
      #- 80:80
      #- 22:22
    networks:
      zetwork:
        ipv4_address: 10.4.1.3
  wg-easy:
    container_name: club-wg
    image: ghcr.io/wg-easy/wg-easy
    environment:
      LANG: en
      WG_HOST: 130.127.149.147
      PASSWORD_HASH: "$$2a$$12$$2UXua/HRT/LkcHZ50sI4NON5.PXCXeliV1e7khJ3093k4E8xNpeHm" # shadowwizard
      PORT: 80
      WG_PORT: 1195
      WG_DEFAULT_ADDRESS: 10.4.2.x
      WG_ALLOWED_IPS: 10.4.0.0/16
      WG_DEVICE: eth1
      UI_TRAFFIC_STATS: true
      UI_CHART_TYPE: 1
      UI_ENABLE_SORT_CLIENTS: true
    volumes:
      - ./wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    labels:
      traefik.enable: "true"
      traefik.docker.network: "zaefik"
      traefik.http.routers.club-wg.rule: "Host(`club-wg.lab.cucyber.net`)"
      traefik.http.services.club-wg.loadbalancer.server.port: "80"
      traefik.http.routers.club-wg.entrypoints: "web"
    networks:
      vmbr1:
        ipv4_address: 10.3.1.3
      zaefik:
      zetwork:
        ipv4_address: 10.4.1.2
        
networks:
  zetwork:
    ipam:
      driver: default
      config:
        - subnet: 10.4.1.0/24
          gateway: 10.4.1.1
  vmbr1:
    external: true
  zaefik:
    external: true
